[tox]
minversion = 3.6
ignore_basepython_conflict = True

[doc8]
ignore = D001
extensions = .rst, .yaml

[testenv:docs]
passenv = GH_ACTIONS_*
deps =
    -r{toxinidir}/doc/requirements.txt
commands =
    sphinx-build -W --keep-going -b html doc/source/ doc/build/html

[testenv:docs-auto]
deps =
    -r{toxinidir}/doc/requirements.txt
allowlist_externals = rm
commands =
    rm -rf doc/build
    sphinx-autobuild --port 8890 doc/source/ doc/build/html

[testenv:linkcheck]
allowlist_externals = sphinx-build
commands =
    sphinx-build -b linkcheck doc/source/ doc/build/linkcheck
