[tox]
minversion = 3.6
ignore_basepython_conflict = True
envlist = event-tests, docs, linkcheck

[doc8]
ignore = D001
extensions = .rst, .yaml

[testenv:event-tests]
commands =
    python -m unittest \
        fg-runtime/tests/test_context.py \
        fg-runtime/tests/test_logger.py \
        fg-events/fg-cts-event/tests/test_ctsevent.py \
        fg-events/fg-dds-event/tests/test_ddsevent.py \
        fg-events/fg-lts-event/tests/test_ltsevent.py \
        fg-events/fg-obss3-event/tests/test_obss3event.py \
        fg-events/fg-smn-event/tests/test_smnevent.py \
        fg-events/fg-dms4kafka-event/tests/test_dms4kafkaevent.py \
        fg-events/fg-dms4rocketmq-event/tests/test_dms4rocketmqevent.py \
        fg-events/fg-kafkaopensource-event/tests/test_kafkaopensourceevent.py

[testenv:docs]
passenv = GH_ACTIONS_*
deps =
    -r{toxinidir}/doc/requirements.txt
commands =
    sphinx-build -W --keep-going -b html doc/source/ doc/build/html

[testenv:docs-auto]
deps =
    -r{toxinidir}/doc/requirements.txt
allowlist_externals = rm
commands =
    rm -rf doc/build
    sphinx-autobuild --port 8890 doc/source/ doc/build/html

[testenv:linkcheck]
allowlist_externals = sphinx-build
commands =
    sphinx-build -b linkcheck doc/source/ doc/build/linkcheck
