# prefix will be prepended to all resource names
variable "prefix" {
  type    = string
  default = "set in variables.tfvars"
}

# description of the function
variable "description" {
  type    = string
  default = "set in variables.tfvars"
}

# FunctionGraph: Function name
variable "function_name" {
  type    = string
  default = "set in variables.tfvars"
}

variable "image_url" {
  type    = string
  default = "set in variables.tfvars"
}

# name of zip file to deploy, generated by 'mvn package' command
variable "zip_file_name" {
  type    = string
  default = "set in variables.tfvars"
}

# Resource tag:
variable "tag_app_group" {
  type    = string
  default = "set in variables.tfvars"
}

variable "API_GATEWAY_INSTANCE_ID" {
  type = string
  default = "set in variables.tfvars"
}
