#!.venv/bin/python3
import requests
from requests import HTTPError
import json
import os
import base64

from string import Template

mainForm=Template('''
..
   _This file is auto-generated by createLibraryDocs.js. Do not edit it directly.
   
.. _bundled_libraries:

Bundled Libraries
========================

Bundled libraries can be used for **event** and **http** functions **build from scratch**.

If you want to use a different version of a runtime-included library,
you can do this by bundling it with your function in your deployment package
or by adding it as a dependency.

For libraries bundled with a Python runtime version see following pages:

.. toctree::
   :maxdepth: 1
   
$DATA
                     
''')                  

versionForm=Template('''
..
   _This file is auto-generated by createLibraryDocs.js. Do not edit it directly.

Bundled third-party components in the $VERSION
=================================================================

Following list shows the bundled third-party components integrated with $VERSION runtime for FunctionGraph.

.. list-table:: Bundled libraries with **$VERSION**
    :header-rows: 1

    * - Name
      - Version

$DATA

''')


project_id = os.environ.get("OTC_SDK_PROJECTID")

url = f"https://functiongraph.eu-de.otc.t-systems.com/v2/{project_id}/fgs/functions"


def token_iam(username, password, domain, project="eu-de", https_insecure=False):
    """authenticate a user by password"""
    auth = {
        "auth": {
            "identity": {
                "methods": ["password"],
                "password": {
                    "user": {
                        "name": username,
                        "password": password,
                        "domain": {"name": domain},
                    }
                },
            },
            "scope": {"domain": {"name": domain}, "project": {"id": project}},
        }
    }

    _session = requests.session()
    authstr = json.dumps(auth, indent=4)

    _url = "https://iam.eu-de.otc.t-systems.com:443"

    if "X-Auth-Token" in _session.headers:
        del _session.headers["X-Auth-Token"]

    if https_insecure:
        response = _session.post(
            _url + "/v3/auth/tokens",
            data=authstr,
            verify=False,
            headers={"Content-Type": "application/json;charset=utf8"},
        )
    else:
        response = _session.post(
            _url + "/v3/auth/tokens",
            data=authstr,
            headers={"Content-Type": "application/json;charset=utf8"},
        )
    if response.status_code != 201:
        raise HTTPError(response=response)

    headers = response.headers
    token = headers["x-subject-token"]

    return token


def delete_function(func_urn: str):
    headers = {
        "x-auth-token": token,
        "Content-Type": "application/json;charset=utf8",
    }

    delurl = f"{url}/{func_urn}"[:-7]

    r = requests.request("DELETE", delurl, headers=headers)
    
    if r.status_code != 204:
        raise HTTPError(response=r)



####################################################################
# Create Function (base)
####################################################################
def create_function(func_name: str, handler_name: str, version: str):

    code = base64.b64encode(open("index.py", "rb").read()).decode("utf-8")

    attrs = {
        "func_name": func_name,
        "package": "default",
        "runtime": version,
        "timeout": 30,
        "handler": handler_name,
        "memory_size": 128,
        "code_type": "inline",
        "func_code": {"file": code},
    }

    headers = {
        "x-auth-token": token,
        "Content-Type": "application/json;charset=utf8",
    }

    r = requests.request("POST", url, headers=headers, data=json.dumps(attrs))
    return json.loads(r.text)


def call_function(func_urn: str):
    headers = {
        "x-auth-token": token,
        "Content-Type": "application/json;charset=utf8",
    }

    body = {
        "key": "Hello FunctionGraph",
    }
    payload = json.dumps(body)

    r = requests.request(
        "POST",
        f"{url}/{func_urn}/invocations",
        headers=headers,
        data=payload.encode("utf-8"),
    )
    return json.loads(r.text)


if __name__ == "__main__":
    token = token_iam(
        username=os.environ.get("OTC_USER_NAME"),
        password=os.environ.get("OTC_USER_PASSWORD"),
        domain=os.environ.get("OTC_DOMAIN_NAME"),
        project=project_id,
    )

    python_version = [
        "Python3.12",
        "Python3.10",
        "Python3.9",
        "Python3.6",
        "Python2.7",
    ]
    
    
    mainDATA = ""
    
    for version in python_version:
        mainDATA += f"    {version} <bundled_libraries_{version}>\n"
        
    print(mainForm.substitute(VERSION=version, DATA=mainDATA))
    
    currentfolder = os.path.dirname(os.path.abspath(__file__))
    
    writeFile = open(os.path.join(currentfolder, "../../../doc/source/devguide/bundled_libraries/_index.rst"), "w")
    writeFile.write(mainForm.substitute(VERSION=version, DATA=mainDATA))
    writeFile.close()

    for version in python_version:
        print(f"Creating Function for {version} ...")
        func_name = f"python-get-libraries-{version.lower().replace('.', '-')}"

        handler_name = "index.handler"

        fg = create_function(
            func_name=func_name, handler_name=handler_name, version=version
        )

        func_urn = fg["func_urn"]

        result = call_function(func_urn)
        
        body = result.get("body")
        
        packages = json.loads(body).get("packages")
        
        sorted_packages = sorted(packages, key=lambda x: x["package"])
        
        data =""
        
        for package in sorted_packages:
            data += f"    * - {package['package']}\n      - {package['version']}\n\n"
            
        print(versionForm.substitute(VERSION=version, DATA=data))
        
        writeVFile = open(os.path.join(currentfolder, f"../../../doc/source/devguide/bundled_libraries/bundled_libraries_{version}.rst"), "w")
        writeVFile.write(versionForm.substitute(VERSION=version, DATA=data))
        writeVFile.close()
        
        

        delete_function(func_urn=func_urn)
